### PR TITLE
Update .bash_aliases

### PR DESCRIPTION
**Pull request by OtakuNekoP**

### CODE REVIEW

**Comment by mo10** [comment]
`alias 。、="./"` not working.

**Comment by OtakuNekoP** [comment]
> `alias 。、="./"` not working.

image
It works.

**Comment by mo10** [comment]
> > `alias 。、="./"` not working.
> 
> image
> It works.

Where can it be used?

**Comment by OtakuNekoP** [comment]
> > > `alias 。、="./"` not working.
> > 
> > 
> > image
> > It works.
> 
> Where can it be used?

I think .bash_aliases may not be used in paras.

**Pull request merged**
